.\"
.\"
.\"   Authors:
.\"    Jean-Jacques Sarton		<jj.sarton@t-onlime.de>	 
.\"
.\"   This software is Copyright 1996 by the above mentioned author(s), 
.\"   All Rights Reserved.
.\"
.\"   The license which is distributed with this software in the file COPYRIGHT
.\"   applies to this software.
.\"
.\"
.\"
.TH radvc 8 "25 Jan 2012" "v0.1" ""
.SH NAME
radvc \- complete / generate a resolv.conf file according to radvd information
.SH SYNOPSIS
.B radvc
.B "[ \-f ] [ \-v ] [ \-r resolv-conf-file]"

.SH DESCRIPTION
.B radvc
complete / generate a resolv.conf file according to the information send by
.B radvd
(
.B RDNSS
and
.B DNSSL
).

.B radvc
will be helpfull for the case that the system is only configured via radvd,
or if the wanted values are not set by the dhcp client programm. If we have
an IPv6 VPN connection,
.B radvc
will build a new resolv.conf file and restore the previous if the connection
is closed.


.SH OPTIONS
 
.TP
.BR "\-f"
The server is started in foreground and some debug messages will be printed
out.

.TP
.BR "\-r"
specify the file to be created. default is /etc/resolv.conf.


.TP
.BR "\-d"
specify the directory where /etc/resolv.conf is temporary saved. This allows
us to restore the old configurations file. Default is /tmp

.TP
.BR "\-v"
Print the version number and exit.

.SH FILES

.nf
/usr/sbin/radvcd
.fi
.SH BUGS

There certainly are some bugs. If you find them or have other
suggestions please contact the author.

.SH "SEE ALSO"

.BR radvd (8),
.BR radvd.conf (5)
.SH AUTHORS

.nf
Jean-Jacques Sarton		<jj.sarton@t-onlime.de>
.fi
