.\"
.\"
.\"   Authors:
.\"    Jean-Jacques Sarton		<jj.sarton@t-onlime.de>	 
.\"
.\"   This software is Copyright 1996 by the above mentioned author(s), 
.\"   All Rights Reserved.
.\"
.\"   The license which is distributed with this software in the file COPYRIGHT
.\"   applies to this software.
.\"
.\"
.\"
.TH radvc 8 "25 Jan 2012" "v0.1" ""
.SH NAME
radvc \- complete / generate a resolv.conf file according to radvd information
.SH SYNOPSIS
.B radvc
.B "[ \-f ] [ \-v ] [ \-r resolv-conf-file] [ \-d save-directory ] [ \-i [ vpn-interface] [ \-p pid-file ]" 

.SH DESCRIPTION
.B radvc
complete / generate a resolv.conf file according to the information send by
.B radvd
(
.B RDNSS
and
.B DNSSL
).

.B radvc
will be helpfull for the case that the system is only configured via radvd,
or if the wanted values are not set by the dhcp client programm. If we have
an IPv6 VPN connection,
.B radvc
will build a new resolv.conf file and restore the previous if the connection
is closed.


.SH OPTIONS
 
.TP
.BR "\-f"
The server is started in foreground and some debug messages will be printed
out.

.TP
.BR "\-r resolv-conf-file"
specify the file to be created. default is /etc/resolv.conf.


.TP
.BR "\-d save-directory"
specify the directory where /etc/resolv.conf is temporary saved. This allows
us to restore the old configurations file. Default is /tmp.

.TP
.BR "\-i vpn-interface"
If radvc is always started and you want to be able to connect to a VPN-server,
you can give the name of the VPN interface here. This make shure that after
the VPN connection and stopping the right resolv.conf file will be correctly
restored and that the name server entries are in the right order.


.TP
.BR "\-p pid-file"
create a pid file,

.TP
.BR "\-v"
Print the version number and exit.

.SH SIGNALS

.BR "radvc"
will restore the original resolv.conf file and ternminate
if the following signals are received:
.B SIGHUP SIGINT SIGQUIT SIGTERM.
The signals
.B SIGUSR1
and
.B SIGUSR2
can be used for signaling that the
.B "VPN"
connection is available or not provided. 
.B radvc
will on receipt of these signals restore the original resolv.conf
file or reinstall the VPN specific resolv.conf file.

.SH FILES

.nf
/usr/sbin/radvcd
.fi
.SH BUGS

There certainly are some bugs. If you find them or have other
suggestions please contact the author.

.SH "SEE ALSO"

.BR radvd (8),
.BR radvd.conf (5)
.SH AUTHORS

.nf
Jean-Jacques Sarton		<jj.sarton@t-onlime.de>
.fi
