#!/bin/sh
# File tinc-up

# Set the following according to you needs
MN_IF=eth0                 # the main interface to the LAN
VPN_SUBNET_NR=3            # the subnet forseen for VPN
VPN_SERVER_SUFFIX=1        # The adresse of the VPN tap is the <prefix>::$VPN_SERVER_SUFFIX
SEARCH_LIST=localnet       # The domain name for your LAN

# calc dynamic value
server_ip=`ip -6 ro sh dev $MN_IF | grep '::/64 via' | awk '{ print $3 }'`
vpn_subnet=`ip -6 ro sh dev $MN_IF | grep '::/64 via' | sed 's/::.*/:'$VPN_SUBNET_NR'::\/64/'`
vpn_server_ip=`echo $vpn_subnet | sed "s@/64@$VPN_SERVER_SUFFIX@"`

ip link set dev $INTERFACE up 
ip link set mtu 1280 dev $INTERFACE

ip ad ad $vpn_server_ip/54 dev $INTERFACE
ip ro ad $vpn_subnet via $vpn_server_ip dev $INTERFACE

function startRadvd()
{
   cat >/tmp/radvd.conf <<!
interface $INTERFACE
{
    AdvSendAdvert on;
    MinRtrAdvInterval 300;
    MaxRtrAdvInterval 600;
    prefix $vpn_subnet
    {
        AdvOnLink on;
        AdvAutonomous on;
        AdvRouterAddr on;
    };
    RDNSS $server_ip { };
    DNSSL $SEARCH_LIST { };
};
!
    chmod 554 /tmp/radvd.conf
    sleep 1
    radvd -p /tmp/radvd.pid -C /tmp/radvd.conf -u radvd
    sleep 1
    ninsd -i $INTERFACE -p /tmp/ninsd.pid
}

startRadvd $vpn_subnet &
